.*: Assembler messages:
.*: Error: illegal operands `aif.maskand m0,m1'
.*: Error: illegal operands `aif.maskand m0,m1,m2,m3'
.*: Error: illegal operands `aif.masknot m0'
.*: Error: illegal operands `aif.masknot m0,m1,m2'
.*: Error: illegal operands `aif.maskpopc a0'
.*: Error: illegal operands `aif.maskpopc a0,m1,m2'
.*: Error: illegal operands `aif.fadd.ps ft0,ft1'
.*: Error: illegal operands `aif.fadd.ps ft0,ft1,ft2,ft3'
.*: Error: illegal operands `aif.fmadd.ps ft0,ft1,ft2'
.*: Error: illegal operands `aif.fsqrt.ps ft0'
.*: Error: illegal operands `aif.mova.m.x'
.*: Error: illegal operands `aif.mova.m.x a0,a1'
.*: Error: illegal operands `aif.maskand a0,m1,m2'
.*: Error: illegal operands `aif.maskand m0,a0,m2'
.*: Error: illegal operands `aif.maskand m0,m1,a0'
.*: Error: illegal operands `aif.masknot a0,m1'
.*: Error: illegal operands `aif.maskor a0,m1,m2'
.*: Error: illegal operands `aif.maskxor m0,a0,m2'
.*: Error: illegal operands `aif.maskpopc m0,m1'
.*: Error: illegal operands `aif.bitmixb m0,a1,a2'
.*: Error: illegal operands `aif.amoaddl.w m0,a1,0\(a2\)'
.*: Error: illegal operands `aif.fadd.ps a0,ft1,ft2'
.*: Error: illegal operands `aif.fadd.ps ft0,a0,ft2'
.*: Error: illegal operands `aif.fadd.ps ft0,ft1,a0'
.*: Error: illegal operands `aif.fsqrt.ps a0,ft1'
.*: Error: illegal operands `aif.bitmixb ft0,a1,a2'
.*: Error: illegal operands `aif.packb a0,ft0,a2'
.*: Error: illegal operands `aif.feqm.ps ft0,ft1,ft2'
.*: Error: illegal operands `aif.fsetm.pi ft0,ft1'
.*: Error: illegal operands `aif.maskand m8,m1,m2'
.*: Error: illegal operands `aif.masknot m0,m8'
.*: Error: .*8.*
.*: Error: .*18446744073709551615.*
.*: Error: .*256.*
.*: Error: .*18446744073709551615.*
.*: Error: .*256.*
.*: Error: .*16.*
.*: Error: .*18446744073709551615.*
.*: Error: improper shift amount \(32\)
.*: Error: improper shift amount \(32\)
.*: Error: improper shift amount \(32\)
.*: Error: .*32.*
